# Generated by Django 4.2.2 on 2023-07-03 06:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.FileField(blank=True, max_length=256, null=True, upload_to=api.models.save_profile_image)),
            ],
        ),
    ]
